#!/bin/sh
# demo.sh — build and run a kavkash demo container with YOUR shell
# histories COPIED into the image (nothing mounted, nothing installed on
# the host).
#
# Single self-contained file: the base Dockerfile and the container
# entrypoint are embedded below and generated into a temp build context
# at run time, so this script works from anywhere — copied to /tmp, or
# piped straight from the repo exactly like install.sh:
#
#   curl -fsSL https://raw.githubusercontent.com/altunyurt/kavkash/main/demo.sh | dash
#
# Existing history files (~/.bash_history, ~/.zsh_history, fish_history,
# atuin history.db) are copied into the image; missing ones are skipped.
# The entrypoint imports them into history.db at container start
# (idempotent). On build failure the context is left in place for
# debugging.
#
# Usage:
#   ./demo.sh                 build + run the demo daemon container
#   PERSIST=1 ./demo.sh       keep history.db across container restarts
#   IMAGE=... NAME=... ./demo.sh   overrides

set -eu

IMAGE=${IMAGE:-kavkash:demo}
NAME=${NAME:-kavkash-demo}
PERSIST=${PERSIST:-0}

command -v docker > /dev/null 2>&1 || { echo "demo.sh: docker not found" >&2; exit 1; }

stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT

# --- base image Dockerfile: kavkash via the documented curl|sh flow ----
cat > "$stage/Dockerfile" <<'DEOF'
# kavkash demo image (Dockerfile generated by demo.sh).
# Debian 13 pinned: kavkash needs fzf >= 0.54; trixie ships 0.60,
# bookworm's 0.38 would silently disable the picker.
FROM debian:13-slim

# socat (socket daemon), sqlite3 (store), mawk (processor), fzf (picker),
# bash/zsh/fish (the shells the hooks integrate with), curl (installer),
# ca-certificates (slim ships none — curl needs them for TLS).
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        bash zsh fish \
        socat sqlite3 mawk fzf curl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# Install kavkash with the EXACT documented one-liner, piped to dash.
# No systemd in a container and no histories exist at build time, so the
# import prompt is answered "no" — the entrypoint imports the histories
# copied into the image at container start. bash -o pipefail: dash alone
# can't report a broken pipe, and a dead curl would otherwise look like
# a successful (empty) install.
RUN bash -o pipefail -c 'export KAVKASH_NO_SYSTEMD=1 KAVKASH_IMPORT=0; curl -fsSL https://raw.githubusercontent.com/altunyurt/kavkash/main/install.sh | dash'

# The container runs as root, but debian images don't set the USER env
# var — import.sh's atuin path expands $USER, and the released installer
# predates the ${USER:-$(id -un)} fallback.
ENV USER=root

COPY entrypoint.sh /usr/local/bin/kavkash-entrypoint
RUN chmod +x /usr/local/bin/kavkash-entrypoint

# rc files wired at build so every interactive shell (docker exec
# included) lands in a kavkash session; HISTFILE keeps interactive bash
# from appending to the copied host history.
RUN mkdir -p /root/.config/fish \
 && printf '\nHISTFILE=/root/.kavkash-bash-history\n[ -f /root/.local/share/kavkash/functions.bash ] && source /root/.local/share/kavkash/functions.bash\n' >> /root/.bashrc \
 && printf '\n[ -f /root/.local/share/kavkash/functions.zsh ] && source /root/.local/share/kavkash/functions.zsh\n' >> /root/.zshrc \
 && printf '\nif test -f /root/.local/share/kavkash/functions.fish\n    source /root/.local/share/kavkash/functions.fish\nend\n' >> /root/.config/fish/config.fish

ENTRYPOINT ["/usr/local/bin/kavkash-entrypoint"]
CMD ["bash"]
DEOF

# --- container entrypoint: import histories, then start the daemon ------
cat > "$stage/entrypoint.sh" <<'EEOF'
#!/bin/sh
# kavkash demo container entrypoint (generated by demo.sh).
# kavkash is already installed in the image; this imports the history
# files copied in at build time (idempotent, picks up new commands on
# every start), then starts the daemon: with a TTY (docker run -it) it
# backgrounds the daemon and execs the requested shell; without one
# (docker run -d) the daemon runs in the foreground as PID 1 and shells
# attach via docker exec.
set -eu

KAV_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/kavkash"
KAV_SOCK="${XDG_RUNTIME_DIR:-/tmp}/kavkash/history.sock"

"$KAV_DATA_HOME/import.sh" --all

wait_for_daemon() {
    i=0
    while [ "$i" -lt 100 ] && [ ! -S "$KAV_SOCK" ]; do
        sleep 0.1
        i=$((i + 1))
    done
    if [ ! -S "$KAV_SOCK" ]; then
        echo "kavkash: daemon did not come up (see docker logs)" >&2
        exit 1
    fi
}

if [ -t 0 ] && [ $# -gt 0 ]; then
    "$KAV_DATA_HOME/server.sh" &
    wait_for_daemon
    exec "$@"
fi

exec "$KAV_DATA_HOME/server.sh"
EEOF
chmod +x "$stage/entrypoint.sh"

# --- copy the user's history files into the build context ---------------
hist_count=0
# plaintext atuin stores (v17-) only; encrypted v18+ rows need the atuin
# binary inside the container, so copying the db alone won't import those
add_copy() {
    [ -f "$1" ] || return 0
    cp "$1" "$stage/$(basename "$1")"
    printf 'COPY %s %s\n' "$(basename "$1")" "$2" >> "$stage/Dockerfile"
    hist_count=$((hist_count + 1))
}
add_copy "$HOME/.bash_history"                  /root/.bash_history
add_copy "$HOME/.zsh_history"                   /root/.zsh_history
add_copy "$HOME/.local/share/fish/fish_history" /root/.local/share/fish/fish_history
add_copy "$HOME/.local/share/atuin/history.db"  /root/.local/share/atuin/history.db

echo "demo.sh: building image (kavkash via curl|dash, $hist_count history file(s) copied in)"
if ! docker build -q -t "$IMAGE" "$stage"; then
    trap - EXIT
    echo "demo.sh: image build failed — context left at $stage for debugging" >&2
    exit 1
fi

# --- run: daemon container; attach shells with docker exec --------------
mounts=""
[ "$PERSIST" = 1 ] && mounts="-v kavkash-demo-data:/root/.local/share/kavkash"
docker run --rm -d --name "$NAME" $mounts "$IMAGE"

echo "container '$NAME' is running (kavkash daemon, your history imported from the image)."
echo "  docker exec -it $NAME bash    # or: fish / zsh"
echo "stop:  docker stop $NAME"
echo "rebuild with fresh history:  ./demo.sh   (re-copies + rebuilds)"
