#!/bin/sh
# demo.sh — build and run a kavkash demo container with YOUR shell
# histories COPIED into the image (nothing mounted, nothing installed on
# the host).
#
# Single self-contained file: the base Dockerfile and the container
# entrypoint are embedded below and generated into a temp build context
# at run time, so it works from anywhere — including piped straight
# from the repo, exactly like install.sh:
#
#   curl -fsSL https://raw.githubusercontent.com/altunyurt/kavkash/main/demo.sh | dash
#
# Existing history files (bash/zsh/fish/atuin) are copied into the image
# (missing ones skipped) and imported at container start (idempotent).
# On build failure the context is left in place for debugging.
#
# Usage:
#   ./demo.sh                 build + run the demo daemon container
#   PERSIST=1 ./demo.sh       keep history.db across container restarts
#   IMAGE=... NAME=... ./demo.sh   overrides

set -eu

IMAGE=${IMAGE:-kavkash:demo}
NAME=${NAME:-kavkash-demo}
PERSIST=${PERSIST:-0}

command -v docker > /dev/null 2>&1 || { echo "demo.sh: docker not found" >&2; exit 1; }

stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT

# --- base image Dockerfile: kavkash via the documented curl|sh flow ----
cat > "$stage/Dockerfile" <<'DEOF'
# kavkash demo image (Dockerfile generated by demo.sh).
# Debian 13 pinned: kavkash needs fzf >= 0.54 — trixie ships 0.60,
# bookworm's 0.38 would silently disable the picker.
FROM debian:13-slim

# ca-certificates: absent from slim, curl needs it for TLS.
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        bash zsh fish socat sqlite3 mawk fzf curl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# The documented one-liner, piped to dash. No systemd and no histories at
# build time, so the import prompt is answered "no" — the entrypoint
# imports the copied histories at container start. bash -o pipefail: a
# dead curl must fail the build, not look like an empty install.
RUN bash -o pipefail -c 'export KAVKASH_NO_SYSTEMD=1 KAVKASH_IMPORT=0; curl -fsSL https://raw.githubusercontent.com/altunyurt/kavkash/main/install.sh | dash'

# Container runs as root, but debian doesn't set USER and import.sh's
# atuin path expands $USER.
ENV USER=root

COPY entrypoint.sh /usr/local/bin/kavkash-entrypoint
RUN chmod +x /usr/local/bin/kavkash-entrypoint

# rc wiring so every interactive shell (docker exec included) lands in a
# kavkash session; HISTFILE keeps interactive bash off the copied host
# history.
RUN mkdir -p /root/.config/fish \
 && printf '\nHISTFILE=/root/.kavkash-bash-history\n[ -f /root/.local/share/kavkash/functions.bash ] && source /root/.local/share/kavkash/functions.bash\n' >> /root/.bashrc \
 && printf '\n[ -f /root/.local/share/kavkash/functions.zsh ] && source /root/.local/share/kavkash/functions.zsh\n' >> /root/.zshrc \
 && printf '\nif test -f /root/.local/share/kavkash/functions.fish\n    source /root/.local/share/kavkash/functions.fish\nend\n' >> /root/.config/fish/config.fish

ENTRYPOINT ["/usr/local/bin/kavkash-entrypoint"]
CMD ["bash"]
DEOF

# --- container entrypoint: import histories, then start the daemon ------
cat > "$stage/entrypoint.sh" <<'EEOF'
#!/bin/sh
# kavkash demo container entrypoint (generated by demo.sh): imports the
# history files copied in at build time (idempotent), then starts the
# daemon — with a TTY (docker run -it) it backgrounds the daemon and
# execs the requested shell; without one (docker run -d) the daemon runs
# in the foreground as PID 1 and shells attach via docker exec.
set -eu

KAV_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/kavkash"
KAV_SOCK="${XDG_RUNTIME_DIR:-/tmp}/kavkash/history.sock"

"$KAV_DATA_HOME/import.sh" --all

wait_for_daemon() {
    i=0
    while [ "$i" -lt 100 ] && [ ! -S "$KAV_SOCK" ]; do
        sleep 0.1
        i=$((i + 1))
    done
    if [ ! -S "$KAV_SOCK" ]; then
        echo "kavkash: daemon did not come up (see docker logs)" >&2
        exit 1
    fi
}

if [ -t 0 ] && [ $# -gt 0 ]; then
    "$KAV_DATA_HOME/server.sh" &
    wait_for_daemon
    exec "$@"
fi

exec "$KAV_DATA_HOME/server.sh"
EEOF
chmod +x "$stage/entrypoint.sh"

# --- copy the user's shell history files into the build context ---------
hist_count=0
add_copy() {
    [ -f "$1" ] || return 0
    cp "$1" "$stage/$(basename "$1")"
    printf 'COPY %s %s\n' "$(basename "$1")" "$2" >> "$stage/Dockerfile"
    hist_count=$((hist_count + 1))
}
add_copy "$HOME/.bash_history"                  /root/.bash_history
add_copy "$HOME/.zsh_history"                   /root/.zsh_history
add_copy "$HOME/.local/share/fish/fish_history" /root/.local/share/fish/fish_history

# --- atuin: mounted read-only, never baked into the image ---------------
# Shell histories are copied because the container's shells write to them
# (taint); atuin records nothing inside the container, so its store can be
# mounted ro instead — and must be: the key file is a secret, and a copy
# in a layer is a copy forever (immutable image layers, distribution).
# The real db path comes from atuin's own config (see `atuin info`); it
# lands in the container at import.sh's default path.
atuin_mounts=""
atuin_db="$HOME/.local/share/atuin/history.db"
if [ -f "$HOME/.config/atuin/config.toml" ]; then
    p=$(sed -n 's/^[[:space:]]*db_path[[:space:]]*=[[:space:]]*"\(.*\)"/\1/p' "$HOME/.config/atuin/config.toml" | head -1)
    [ -n "$p" ] && atuin_db=$p
fi
case "$atuin_db" in "~/"*) atuin_db="$HOME/$(printf '%s' "$atuin_db" | sed 's|^~/||')" ;; esac
atuin_db=$(printf '%s' "$atuin_db" | sed "s/\$USER/$(id -un)/g")
if [ -f "$atuin_db" ]; then
    atuin_mounts="-v $atuin_db:/root/.local/share/atuin/history.db:ro"
    [ -f "$HOME/.local/share/atuin/key" ] \
        && atuin_mounts="$atuin_mounts -v $HOME/.local/share/atuin/key:/root/.local/share/atuin/key:ro"
fi

echo "demo.sh: building image (kavkash via curl|dash, $hist_count history file(s) copied in)"
if ! docker build -q -t "$IMAGE" "$stage"; then
    trap - EXIT
    echo "demo.sh: image build failed — context left at $stage for debugging" >&2
    exit 1
fi

# --- run: daemon container; attach shells with docker exec --------------
mounts=""
[ "$PERSIST" = 1 ] && mounts="-v kavkash-demo-data:/root/.local/share/kavkash"
docker run --rm -d --name "$NAME" $mounts $atuin_mounts "$IMAGE"

if [ -n "$atuin_mounts" ]; then
    echo "atuin: store mounted read-only at /root/.local/share/atuin/history.db (key stays on the host)"
fi

echo "container '$NAME' is running (kavkash daemon, your history imported from the image)."
echo "  docker exec -it $NAME bash    # or: fish / zsh"
echo "stop:  docker stop $NAME"
echo "rebuild with fresh history:  ./demo.sh   (re-copies + rebuilds)"
